name: al_akhtan_app
description: A new Flutter project for Al-Akhtan brand.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/banner_bg.png
    - assets/images/red_hijab.png
    - assets/images/white_hijab.png
    - assets/images/mix_hijab.png
